
services:
  backend:
    build: ./backend
    container_name: ctf_backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app           
      - /app/node_modules        
    environment:
      - NODE_ENV=development

  frontend:
    build: ./frontend
    container_name: ctf_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend                 